version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
       - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative,lang=go1.23 --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative